[package]
name = "panser"
version = "0.0.3"
authors = ["Christopher Field <cfield2@gmail.com>"]

[dependencies]
bincode = "0.7"
byteorder = "1"
clap = "2.23"
serde = "0.9"
serde_json = "0.9"
rmp-serde = "0.12"
